# 鼠标支持（手机/VSCode都方便）
set -g mouse on

# 大历史
set -g history-limit 100000

# 窗口编号
set -g base-index 1
setw -g pane-base-index 1

# 新窗口保持当前目录
bind c new-window -c "#{pane_current_path}"

# 状态栏显示机器和时间
set -g status-right '#H %Y-%m-%d %H:%M'

# 不因为窗口关闭退出server
set -g exit-empty off
